#!/usr/bin/env php
<?php
if(!defined('STDIN')) { die("You're unauthorized to view this page."); }

if(!file_exists('./script/wp-script-config.php')) { die("Your script/wp-script-config.php file wasn't found."); }
include_once('./script/wp-script-config.php');

if(!isset($argv[1])) { die("USAGE: ./script/deploy [version-number]\n"); }

$my_version = $argv[1];

// Accepts X.Y.Z, the legacy MemberPress prerelease convention (1.2.3rc1) and
// semver prereleases (1.2.3-rc.1). $m[1] only captures the legacy suffix word.
if(!preg_match('/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+|([a-z_][a-z_-]*)\d+)?$/iD', $my_version, $m)) {
  exit("Improper Version Format\n\n");
}

echo "!! Deploying version \"{$my_version}\"\n";
//print_r($m);

$my_branch = 'master';
if(!empty($m[1]) && !in_array(strtolower($m[1]), array('a','b','rc'))) {
  $my_branch = $m[1];
}

if(!defined('MY_PLUGIN_MAIN_FILE')) {
  define('MY_PLUGIN_MAIN_FILE', WP_SCRIPT_TEXTDOMAIN . '.php');
}

echo "!! Deploying from branch \"{$my_branch}\"\n";

$commands = array();
$commands[] = "/usr/bin/git checkout {$my_branch}";
$commands[] = "/usr/bin/perl -p -i -e 's/^Version: (.*)$/Version: {$my_version}/' ./" . MY_PLUGIN_MAIN_FILE;
$commands[] = './script/mki18n';
$commands[] = './script/rmlb';
$commands[] = './script/cleartrailingwhitespace';
$commands[] = './script/rmtabs';
$commands[] = "/usr/bin/git commit -am 'Bump {$my_branch} to version {$my_version}'";
$commands[] = "/usr/bin/git push origin {$my_branch}";
$commands[] = "/usr/bin/git tag {$my_version}";
$commands[] = "/usr/bin/git push origin {$my_version}";
$commands[] = '/usr/bin/curl -d "apikey=' . MOTHERSHIP_API_KEY . '" ' . MOTHERSHIP_URL . '/versions/deploy/' . MOTHERSHIP_PROJECT_ID . '/' . $my_version;

foreach($commands as $command) { echo "\n$command\n"; system($command); sleep(1); }

echo "\n\n";

