#!/bin/bash
find . -regextype posix-extended \
  -iregex '\./(brand/add-ons|script|test|tmp).*|.*/(node_modules|vendor).*' -prune -o \
  -type f \( -name '*.php' -o -name '*.css' -o -name '*.js' \) \
  -print \
  -exec /usr/bin/perl -p -i -e 's/\r//g' {} +
