#!/bin/bash

shell=$(dirname $(readlink -f $0))"/wpshell.php"

if [ -t 0 ]; then
	while [ true ]; do
		/usr/bin/env php $shell
		if [ $? -eq 0 ]; then break; fi
	done
else
	set -f
	read -s input
	echo $input | /usr/bin/env php $shell stdin
fi

